services:
  # Main application
  - type: web
    name: pokedex-backend
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://pokedex-frontend.onrender.com
      - key: DB_HOST
        value: YOUR_POSTGRES_HOST_HERE
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: YOUR_DB_NAME_HERE
      - key: DB_USER
        value: YOUR_DB_USER_HERE
      - key: DB_PASS
        value: YOUR_DB_PASSWORD_HERE
      - key: REDIS_HOST
        value: YOUR_REDIS_HOST_HERE
      - key: REDIS_PORT
        value: "6379"
